:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Image Builder

Provide Image Builder Summary here

[discrete]
=== Current State

[discrete]
=== Futures

== Getting Started

Starting on the host *workstation.example.com*, let's ssh over to *node1.example.com*.  No password should be required.

.[root@workstation]#
----
ssh node1.example.com
----

Verify that you are on the right host for these exercises.

.[root@node1]#
----
cheat-imagebuilder-checkhost.sh
----

Now you are ready to begin

== Installation & Configuration

=== Packages and Services


[NOTE]
====
_Native command(s) to enable firewalld_
----
systemctl stop IMAGEBUILDER
systemctl disable IMAGEBUILDER
yum install IMAGEBUILDER
systemctl enable --now IMAGEBUILDER
systemctl status -l IMAGEBUILDER
----
====



== Building RHEL 8 Image for Azure

Some instrcutional text

.[root@workstation]#
----
ssh node1.example.com
----

Describe the expected output if necessary

.Command Output
[source,indent=4]
----
Output from previous command
----

== TASK 2

== TASK 3

== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[Deplying Session Recording on Red Hat Enterprise Linux]

[discrete]
== End of Unit

link:../RHEL8-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////

